_format_version: "2.1"
_transform: true

services:
  - name: auth-v1
    url: http://auth:9999/verify
    routes:
      - name: auth-v1
        strip_path: true
        paths:
          - /auth/v1
    plugins:
      - name: cors
      - name: key-auth
        config:
          key_names:
            - apikey
            - authorization
          hide_credentials: true
          key_in_header: true
          key_in_query: true
          run_on_preflight: true

  - name: rest-v1
    url: http://db:3000
    routes:
      - name: rest-v1
        strip_path: true
        paths:
          - /rest/v1
    plugins:
      - name: cors
      - name: key-auth
        config:
          key_names:
            - apikey
            - authorization
          hide_credentials: true
          key_in_header: true
          key_in_query: true
          run_on_preflight: true

  - name: realtime-v1
    url: http://realtime:4000/socket/
    routes:
      - name: realtime-v1-pooler
        strip_path: true
        paths:
          - /realtime/v1
    plugins:
      - name: cors
      - name: key-auth
        config:
          key_names:
            - apikey
            - authorization
          hide_credentials: true
          key_in_header: true
          key_in_query: true
          run_on_preflight: true

  - name: storage-v1
    url: http://storage:5000
    routes:
      - name: storage-v1
        strip_path: true
        paths:
          - /storage/v1
    plugins:
      - name: cors
      - name: key-auth
        config:
          key_names:
            - apikey
            - authorization
          hide_credentials: true
          key_in_header: true
          key_in_query: true
          run_on_preflight: true

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - apikey
        - Authorization
      exposed_headers:
        - Content-Length
        - Content-Range
      credentials: true
      max_age: 3600
      preflight_continue: false
